services:
  app:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=test
    command: >
      sh -c "
        bun install &&
        bun run lint &&
        bun run test:ci &&
        bun run tsc &&
        bun run build &&
        bun run backstage-cli plugin:check
