app:
  title: Buildkite Plugin
  baseUrl: http://localhost:3000

backend:
  listen: 0.0.0.0:7007
  baseUrl: http://localhost:7007

buildkite:
  apiToken: ${BUILDKITE_API_TOKEN}

organization:
  name: Buildkite

proxy:
  '/buildkite/api':
    target: https://graphql.buildkite.com/v1
    headers:
      Authorization: 'Bearer ${BUILDKITE_API_TOKEN}'
