app:
  title: Buildkite Plugin
  baseUrl: http://localhost:3000

backend:
  listen: 0.0.0.0:7007
  baseUrl: http://localhost:7007

organization:
  name: Buildkite

proxy:
  '/buildkite/api':
    target: https://api.buildkite.com/v2
    headers:
      Authorization: 'Bearer ${BUILDKITE_API_TOKEN}'
