config:
  bun: &bun
    docker-compose#v5.4.0:
      run: bun
      config: compose.yaml

steps:
  - label: ":bun: Install modules"
    key: install
    plugins:
      - *bun
    command: bun install --frozen-lockfile
    artifact_paths:
      - "node_modules/**/*"
  - label: ":lint_roller: Lint"
    plugins:
      - *bun
    command: bun run lint
# notify:
#   - slack: "#project-backstage-spotify-plugin"
