steps:
  - label: ':docker: Build and Test'
    command: |
      echo "Building and testing..."
      sleep 5
      echo "GOTEM"
    plugins:
      - docker-compose#v5.4.0:
          run: app
          config: compose.yaml
    artifact_paths:
      - coverage/**/*
      - dist/**/*
# notify:
#   - slack: "#project-backstage-spotify-plugin"
