steps:
  - label: '💀 Test'
    command: yarn test ./src/utils/
    plugins:
      - docker-compose#v5.6.0:
          run: app
          config: compose.yaml
    artifact_paths:
      - coverage/**/*
      - dist/**/*
# notify:
#   - slack: "#project-backstage-spotify-plugin"
