steps:
  - label: ":docker: Build and Test"
    command: |
      bun install
      bun run lint
      bun run tsc
      bun run build
      bun run backstage-cli plugin:check
    plugins:
      - docker-compose#v5.4.0:
          run: app
          config: compose.yaml
    artifact_paths:
      - coverage/**/*
      - dist/**/*

# notify:
#   - slack: "#project-backstage-spotify-plugin"
