steps:
  - label: ':typescript: Lint'
    soft_fail: true
    plugins:
      - docker-compose#v5.4.0:
          run: lint
          config: compose.yaml

  - label: ':jest: Unit Tests'
    plugins:
      - docker-compose#v5.4.0:
          run: test
          config: compose.yaml
    artifact_paths:
      - coverage/**/*
  
  - label: ':package: Build'
    soft_fail: true
    plugins:
      - docker-compose#v5.4.0:
          run: build
          config: compose.yaml
    artifact_paths:
      - dist/**/*

  - label: ':npm: Version Input'
    if: build.branch == 'main'
    key: version-input
    input: |
      What kind of version bump would you like to make?
    fields:
      - select: "Version Bump"
        key: "version-type"
        options:
          - label: "Major (Breaking Changes)"
            value: "major"
          - label: "Minor (New Features)"
            value: "minor"
          - label: "Patch (Bug Fixes)"
            value: "patch"
        required: true

  - label: ':npm: Publish Package'
    if: build.branch == 'main'
    depends_on: version-input
    command: |
      # Extract the version type from the previous step
      VERSION_TYPE=$(buildkite-agent meta-data get version-type)
      echo "Performing $VERSION_TYPE version bump"
      
      # Setup npm credentials
      npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      
      # Bump version according to input
      npm version $VERSION_TYPE --no-git-tag-version
      
      # Publish to npm registry
      npm publish --access public
    plugins:
      - docker-compose#v5.4.0:
          run: node
          config: compose.yaml
          environment:
            - NPM_TOKEN

# notify:
#   - slack: "#project-backstage-spotify-plugin"
