steps:
  - label: ':typescript: Lint'
    key: lint
    plugins:
      - docker-compose#v5.4.0:
          run: lint
          config: compose.yaml

  - label: ':jest: Unit Tests'
    key: unit_tests
    plugins:
      - docker-compose#v5.4.0:
          run: test
          config: compose.yaml
    artifact_paths:
      - coverage/**/*
  
  - label: ':package: Build'
    key: build
    plugins:
      - docker-compose#v5.4.0:
          run: build
          config: compose.yaml
    artifact_paths:
      - dist/**/*

# notify:
#   - slack: "#project-backstage-spotify-plugin"
