steps:
  - label: ":typescript: Lint"
    key: lint
    plugins:
      - docker-compose#v5.4.0:
          run: lint
          config: compose.yaml

  - label: ":jest: Unit Tests"
    key: unit_tests
    plugins:
      - docker-compose#v5.4.0:
          run: test
          config: compose.yaml
    artifact_paths:
      - coverage/**/*

  - label: ":package: Build"
    key: build
    plugins:
      - docker-compose#v5.4.0:
          run: build
          config: compose.yaml
    artifact_paths:
      - dist/**/*

  - label: ":npm: Publish Dry Run"
    branches: "!main"
    key: publish_dry_run
    depends_on: ["build", "unit_tests", "lint"]
    plugins:
      - artifacts#v1.9.4:
          download:
            - "dist/**/*"
      - docker-compose#v5.4.0:
          run: app
          config: compose.yaml
          volumes:
            - "./dist:/app/dist:ro"
# notify:
#   - slack: "#project-backstage-spotify-plugin"
