steps:
  - label: ":typescript: Lint"
    key: lint
    plugins:
      - docker-compose#v5.4.0:
          run: lint
          config: compose.yaml

  - label: ":jest: Unit Tests"
    key: unit_tests
    plugins:
      - docker-compose#v5.4.0:
          run: test
          config: compose.yaml
    artifact_paths:
      - coverage/**/*

  - label: ":package: Build"
    key: build
    plugins:
      - docker-compose#v5.4.0:
          run: build
          config: compose.yaml
    artifact_paths:
      - dist/**/*

  - label: ":npm: Publish Dry Run"
    branches: "!main"
    key: publish_dry_run
    plugins:
      - docker-compose#v5.4.0:
          run: publish
          config: compose.yaml
          mount-buildkite-agent: true
    artifact_paths:
      - dist/**/*
    depends_on: ["build", "unit_tests", "lint"]
# notify:
#   - slack: "#project-backstage-spotify-plugin"
