steps:
  - label: ':typescript: Lint'
    key: lint
    plugins:
      - docker-compose#v5.4.0:
          run: lint
          config: compose.yaml

  - label: ':jest: Unit Tests'
    key: unit_tests
    plugins:
      - docker-compose#v5.4.0:
          run: test
          config: compose.yaml
    artifact_paths:
      - coverage/**/*
  
  - label: ':package: Build'
    key: build
    plugins:
      - docker-compose#v5.4.0:
          run: build
          config: compose.yaml
    artifact_paths:
      - dist/**/*
      - dist-types/**/*

  - label: ':npm: Version Input'
    if: build.branch == 'main'
    depends_on: [lint, unit_tests, build]
    key: version_input
    input: |
      What kind of version bump would you like to make?
    fields:
      - select: "Version Bump"
        key: "version-type"
        options:
          - label: "Major (Breaking Changes)"
            value: "major"
          - label: "Minor (New Features)"
            value: "minor"
          - label: "Patch (Bug Fixes)"
            value: "patch"
        required: true

  - label: ':npm: Publish Package'
    if: build.branch == 'main'
    depends_on: version_input
    command: |
      # Extract the version type from the previous step
      VERSION_TYPE=$(buildkite-agent meta-data get version_type)
      echo "Performing $VERSION_TYPE version bump"

      # Setup npm credentials
      npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN

      # Bump version according to input
      npm version $VERSION_TYPE --no-git-tag-version

      # Build and prepare for publishing
      yarn tsc && yarn build && yarn prepack

      # Publish to npm registry (skip scripts since prepack already ran)
      npm publish --access public --ignore-scripts

      # Restore package.json to original state
      yarn postpack
    plugins:
      - docker-compose#v5.4.0:
          run: node
          config: compose.yaml
          environment:
            - NPM_TOKEN

# notify:
#   - slack: "#project-backstage-spotify-plugin"
