import { PipelineParams } from "./components/Types";

export const mockPipelines: PipelineParams[] = [
  {
    name: "ads-promo-client",
    id: "asd145fg6153df",
    navatarColor: "#D1FAFF",
    navatarImage:
      "https://buildkiteassets.com/emojis/img-buildkite-64/react.png",
    builds: [
      {
        status: "FAILED",
        buildMessage: "Fix issue with user login",
        buildNumber: "123",
        author: {
          avatar: "https://api.dicebear.com/6.x/open-peeps/svg?seed=Author1",
          name: "Jane Doe",
        },
        branch: "main",
        commitId: "a1b2c3d4",
        createdAt: "2024-07-24T09:23:00Z",
        timeElapsed: "36s",
        steps: [
          {
            id: "step1",
            title: "Upload Pipeline",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/pipeline.png",
            status: "PASSED",
            url: "#",
          },
          {
            id: "step2ish",
            title: "Unblocked step",
            command: "script/ci",
            status: "UNBLOCKED",
          },
          {
            id: "step2",
            title: "Build Docker Image",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/docker.png",
            status: "FAILED",
            url: "#",
          },
          {
            id: "step3",
            title: "Linting",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/eslint.png",
            status: "RUNNING",
            url: "#",
          },
          {
            id: "stepWait",
            status: "WAITER",
          },
          {
            id: "step4",
            title: "Unit Tests",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/jest.png",
            status: "BLOCKED",
            url: "#",
          },
          {
            id: "step5",
            title: "Integration Tests",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/cypress.png",
            status: "CANCELED",
            url: "#",
          },
          {
            id: "step6",
            title: "Deploy to Staging",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/kubernetes.png",
            status: "CANCELING",
            url: "#",
          },
          {
            id: "step7",
            title: "Deploy to Production",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/kubernetes.png",
            status: "CREATING",
            url: "#",
          },
          {
            id: "step7ish",
            title: "Blocked Step",
            command: "script/ci",
            status: "BLOCKED",
          },
          {
            id: "step8",
            title: "Security Scan",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/snyk.png",
            status: "FAILING",
            url: "#",
          },
          {
            id: "step8ish",
            title: "Assigned",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/snyk.png",
            status: "ASSIGNED",
            url: "#",
          },
          {
            id: "step85ish",
            title: "Accepted",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/snyk.png",
            status: "ACCEPTED",
            url: "#",
          },
          {
            id: "step9",
            title: "Code Coverage",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/codecov.png",
            status: "NOT_RUN",
            url: "#",
          },
          {
            id: "step10",
            title: "Performance Tests",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/k6.png",
            status: "SCHEDULED",
            url: "#",
          },
          {
            id: "step11",
            title: "Documentation",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/storybook.png",
            status: "SKIPPED",
            url: "#",
          },
          {
            id: "step12",
            title: "Approval",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/github.png",
            status: "WAITING",
            url: "#",
          },
          {
            id: "step13",
            title: "Post-Deployment Check",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/datadog.png",
            status: "WAITING_FAILED",
            url: "#",
          },
          {
            id: "step14",
            title: "Code Review",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/github.png",
            status: "Undetermined",
            url: "#",
          },
        ],
      },
      {
        status: "RUNNING",
        buildMessage: "Add transaction context to all queries",
        buildNumber: "124",
        author: {
          avatar: "https://api.dicebear.com/6.x/open-peeps/svg?seed=Author2",
          name: "John Smith",
        },
        branch: "feature/payments",
        commitId: "e5f6g7h8",
        createdAt: "2024-07-24T10:45:00Z",
        timeElapsed: "2m",
        steps: [
          {
            id: "step1",
            title: "Upload Pipeline",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/pipeline.png",
            status: "PASSED",
            url: "#",
          },
          {
            id: "step2",
            title: "Build Docker Image",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/docker.png",
            status: "PASSED",
            url: "#",
          },
          {
            id: "step3",
            title: "Linting",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/eslint.png",
            status: "RUNNING",
            url: "#",
          },
        ],
      },
      {
        status: "PASSED",
        buildMessage: "Add new feature for payments",
        buildNumber: "125",
        author: {
          avatar: "https://api.dicebear.com/6.x/open-peeps/svg?seed=Author2",
          name: "John Smith",
        },
        branch: "feature/payments",
        commitId: "sdf8d10",
        createdAt: "2024-07-24T10:45:00Z",
        timeElapsed: "17m",
        steps: [
          {
            id: "step1",
            title: "Upload Pipeline",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/pipeline.png",
            status: "PASSED",
            url: "#",
          },
          {
            id: "step2",
            title: "Build Docker Image",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/docker.png",
            status: "PASSED",
            url: "#",
          },
          {
            id: "step3",
            title: "Linting",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/eslint.png",
            status: "RUNNING",
            url: "#",
          },
        ],
      },
    ],
  },
  {
    name: "ads-promo-deploy",
    id: "45j48ktyu85mf",
    navatarColor: "#326DE6",
    navatarImage:
      "https://buildkiteassets.com/emojis/img-buildkite-64/kubernetes.png",
    builds: [
      {
        status: "FAILED",
        buildMessage: "Fix issue with checkout",
        buildNumber: "201",
        author: {
          avatar: "https://api.dicebear.com/6.x/open-peeps/svg?seed=Author3",
          name: "Alice Smith",
        },
        branch: "main",
        commitId: "b1c2d3e4",
        createdAt: "2024-07-24T11:23:00Z",
        timeElapsed: "45s",
        steps: [
          {
            id: "step1",
            title: "Upload Pipeline",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/pipeline.png",
            status: "PASSED",
            url: "#",
          },
          {
            id: "step2",
            title: "Build Docker Image",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/docker.png",
            status: "PASSED",
            url: "#",
          },
          {
            id: "step3",
            title: "Linting",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/eslint.png",
            status: "RUNNING",
            url: "#",
          },
        ],
      },
      {
        status: "RUNNING",
        buildMessage: "Add new payment gateway",
        buildNumber: "202",
        author: {
          avatar: "https://api.dicebear.com/6.x/open-peeps/svg?seed=Author4",
          name: "Bob Johnson",
        },
        branch: "feature/payments",
        commitId: "f6g7h8i9",
        createdAt: "2024-07-24T12:45:00Z",
        timeElapsed: "5m",
        steps: [
          {
            id: "step1",
            title: "Upload Pipeline",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/pipeline.png",
            status: "PASSED",
            url: "#",
          },
          {
            id: "step2",
            title: "Build Docker Image",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/docker.png",
            status: "PASSED",
            url: "#",
          },
          {
            id: "step3",
            title: "Linting",
            command: "script/ci",
            icon: "https://buildkiteassets.com/emojis/img-buildkite-64/eslint.png",
            status: "RUNNING",
            url: "#",
          },
        ],
      },
    ],
  },
];
